### ISSUE TITLE
TiffFileError

### ISSUE THREAD

**Issue by longqianh** [iksungk/CoCoA#1]
Hi iksung! When I ran the code, I got _TiffFileError_ saying the 0.tif and 3A.tif in source/beads are not tif images. I downloaded them and confirmed that they were damaged.

```
raise TiffFileError(f'not a TIFF file {header!r}') from exc
tifffile.tifffile.TiffFileError: not a TIFF file b'vers'
```

Could you check these two files? Thank you!

**Comment by iksungk** [comment]
Thanks for the comment! Unfortunately, it seems like the bandwidth has already reached its limit. I've added a link to a zip file of the repository in Google Drive, available here: https://drive.google.com/file/d/1NSbZEPbJJuKwv6JcknqLJB0iPBAkmFYn/view?usp=drive_link. Hope it helps!

**Comment by longqianh** [comment]
That works. Thanks a lot!
